### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by gepcel** [gepcel/GisViewer#1]
Make a list of what to do, and accept suggestions.

## Todo list

* [x] Update icons.
* [x] Update tooltips.
* [x] Set a default coordinate systems.
* [ ] Change projection system of layer.
* [ ] Chinese version of tooltips.
* [x] Optimise the layout of identify table.
* [x] Esc to exit the feature identify form.
* [ ] Select tool.
* [x] Add some keyboard shortcuts to switch between tools.
* [ ] Save from feature identify form and attribute data table.
